title: Bulk Tag
description: Add-On that allows you to add tags or key/value pairs to large sets of documents.
type: object
documents:
  - query
  - selected
properties:
  key:
    title: Key 
    type: string
    description: Use _tag if you want to add a normal tag. Otherwise provide the name of your key. 
    default: _tag
  value:
    title: Value
    type: string
required:
  - key
  - value 
# Categories are what type of Add-On this is. Used to sort the Add-On in the Add-On menu. 
categories: 
  - bulk
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
